<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Welcome to Notes, test22</name>
   <tag></tag>
   <elementGuidId>2a51a613-4713-4b50-9b8d-366e1484e3d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/main/section/section[2]/article/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Welcome to Notes, test22!&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea732f9e-b00d-4f47-8b5d-f9bae2295713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome to Notes, test22!</value>
      <webElementGuid>25e5a0e5-5e23-4e86-a2f6-f48af823277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/notes/notes-nCpQfdFMXYQOwtVX</value>
      <webElementGuid>0d55bdd4-af41-4444-abfc-1597c636302f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to Notes, test22!</value>
      <webElementGuid>57769b88-8cd7-4ca0-b7c5-4f8425ea3593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-container&quot;]/main[1]/section[@class=&quot;homepage&quot;]/section[@class=&quot;notes-list&quot;]/article[@class=&quot;note-item&quot;]/h3[@class=&quot;note-item__title&quot;]/a[1]</value>
      <webElementGuid>6dd8f016-6499-42f9-8946-2f1eeaeabba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/main/section/section[2]/article/h3/a</value>
      <webElementGuid>d8928204-3eaa-4524-82f0-a0b6ea40573f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Welcome to Notes, test22!')]</value>
      <webElementGuid>e4b224b8-c016-464a-b855-16603640014b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/notes/notes-nCpQfdFMXYQOwtVX')]</value>
      <webElementGuid>c5634253-ef02-4212-8660-db89fa77b406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>7fb615c6-5c0c-4634-82ec-7cb652e2acad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Welcome to Notes, test22!' and @href = '/notes/notes-nCpQfdFMXYQOwtVX' and (text() = 'Welcome to Notes, test22!' or . = 'Welcome to Notes, test22!')]</value>
      <webElementGuid>34711292-2b3b-4180-8d59-15fbf46d18fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
